### ISSUE TITLE
 Whether cuda environment is nesessary

### ISSUE THREAD

**Issue by LiuPearl1** [iliiliiliili/KittiViewer-plus#2]
Hi~ When i run this project, I meet the problrm: 
```
Traceback (most recent call last):
  File "viewer.py", line 53, in <module>
    import second.core.box_np_ops as box_np_ops
  File "/media/vdb/下载/KittiViewer-plus-master/second/core/box_np_ops.py", line 13, in <module>
    box_ops_cc = load_pb11(["./cc/box_ops.cc"], current_dir / "box_ops_cc.so", current_dir)
  File "/media/vdb/下载/KittiViewer-plus-master/second/utils/buildtools/pybind11_build.py", line 90, in load_pb11
    arch = find_cuda_device_arch()
  File "/media/vdb/下载/KittiViewer-plus-master/second/utils/find.py", line 77, in find_cuda_device_arch
    cuda_home = find_cuda()
  File "/media/vdb/下载/KittiViewer-plus-master/second/utils/find.py", line 69, in find_cuda
    "No CUDA runtime is found, using CUDA_HOME='{}'".format(cuda_home))
RuntimeError: No CUDA runtime is found, using CUDA_HOME='None'
```
I wonder if this project must need cuda environment. Looking for your reply, thank you!

**Comment by iliiliiliili** [comment]
Thank you for your interest in the project.
Some bounding box operations are created for cuda, and that's why `box_np_ops` check for it.
I am uncertain if it's easy to replace them now, and, unfortunately, I cannot dedicate time for it in the near future.
If you have time to check and fix it, feel free to open a corresponding pull request.
